name: Build Package

on: [push, pull_request]

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        # Install a specific version of uv.
        version: "0.8.24"
        enable-cache: true

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Install hips2fits_cutout script
      run: |
        uv pip install "cdshealpix>=0.7.0" "numba>=0.59.1"
        git clone https://github.com/cds-astro/hips2fits-cutout.git $HOME/hips2fits-cutout
        echo "PYTHONPATH=$HOME/hips2fits-cutout:\$PYTHONPATH" >> $GITHUB_ENV

    - name: Test with pytest
      run: |
        uv run pytest tests
